# workflow for dev envorinment
# activates on pushing to dev branch
name: Dev Workflow

on:
  push:
    branches:
      - dev

jobs:
  terraform:
    name: Terraform Deploy - Dev
    runs-on: ubuntu-latest

    # set environment variables globally for the job
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    # set the working directory for all steps
    defaults:
      run:
        working-directory: ./deployments

    steps:
      # step to check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # step to set up Terraform for the job
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # step to initialize Terraform
      - name: Terraform Init
        run: terraform init

      # step to create an execution plan for the changes
      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars.dev -out=tfplan

      # step to apply the changes automatically
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
