# Workflow for staging envorinment/branch
name: Staging Workflow

on:
  push:
    branches:
      - staging

jobs:
  terraform:
    name: Terraform Deploy - Staging
    runs-on: ubuntu-latest

    # defines envorinment global variables for the job
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    # set the working directory for all steps
    defaults:
      run:
        working-directory: ./deployments

    steps:
      # check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # step to set up Terraform for the job
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # initialize Terraform
      - name: Terraform Init
        run: terraform init

      # creates an execution plan for the changes using the stagings tfvars file
      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars.staging -out=tfplan
      # apply the changes
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
